# Server Settings
server:
  port: 443
  http:
    port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    log-resolved-exception: false
  thymeleaf:
    prefix: classpath:/static/
    encoding: UTF-8
    cache: false
  web:
    resources:
      static-locations:
        - classpath:/static/
  datasource:
    driver-class-name: org.postgresql.Driver
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  security:
    private-apis:
      - /portal/**
      - /auth/api/**
    cors:
      allow-credentials: true
      allowed-origins:
        - https://${DOMAIN}
        - https://localhost
      allowed-methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed-headers:
        - Authorization
        - Origin
        - Content-Type
        - Accept
        - Accept-Encoding
        - Accept-Language
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Headers
        - Access-Control-Request-Method
        - X-Requested-With
        - X-Auth-Token
        - X-Xsrf-Token
        - Cache-Control
        - Id-Token
      exposed-headers:
    oauth2:
      client:
        registration:
          google:
            scope: openid, profile, email, address, phone
            client-name: Google Login
