version: "3.8"

services:
  postgres-db:
    env_file:
      - ../.env
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ../db/database.sql:/docker-entrypoint-initdb.d/init-0.sql
      - ../db/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
